version: '3.3'
services:
        wordpress:
                depends_on:
                        - mariadb
                image: wordpress:latest
                links:
                        - mariadb:mysql
                environment:
                        - WORDPRESS_DB_USER=wordpress
                        - WORDPRESS_DB_PASSWORD=wordpress
                        - WORDPRESS_DB_NAME=wordpress
                        - WORDPRESS_DB_HOST=mariadb:3306
                ports:
                        - "80:80"
                restart: unless-stopped
                volumes:
                        - ./html:/var/www/html
        mariadb:
                image: mariadb:10.0
                restart: unless-stopped
                environment:
                        - MYSQL_ROOT_PASSWORD=somewordpress
                        - MYSQL_DATABASE=wordpress
                        - MYSQL_USER=wordpress
                        - MYSQL_PASSWORD=wordpress
                command: --max_allowed_packet=2G
                ports:
                        - "3306:3306"
                volumes:
                        - ./mysql:/var/lib/mysql
